package com.lumiere.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatSessionAllPropertiesEquals(ChatSession expected, ChatSession actual) {
        assertChatSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertChatSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatSessionAllUpdatablePropertiesEquals(ChatSession expected, ChatSession actual) {
        assertChatSessionUpdatableFieldsEquals(expected, actual);
        assertChatSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatSessionAutoGeneratedPropertiesEquals(ChatSession expected, ChatSession actual) {
        assertThat(actual)
            .as("Verify ChatSession auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatSessionUpdatableFieldsEquals(ChatSession expected, ChatSession actual) {
        assertThat(actual)
            .as("Verify ChatSession relevant properties")
            .satisfies(a -> assertThat(a.getCustomerId()).as("check customerId").isEqualTo(expected.getCustomerId()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatSessionUpdatableRelationshipsEquals(ChatSession expected, ChatSession actual) {
        // empty method
    }
}
