package com.lumiere.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CollectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionAllPropertiesEquals(Collection expected, Collection actual) {
        assertCollectionAutoGeneratedPropertiesEquals(expected, actual);
        assertCollectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionAllUpdatablePropertiesEquals(Collection expected, Collection actual) {
        assertCollectionUpdatableFieldsEquals(expected, actual);
        assertCollectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionAutoGeneratedPropertiesEquals(Collection expected, Collection actual) {
        assertThat(actual)
            .as("Verify Collection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionUpdatableFieldsEquals(Collection expected, Collection actual) {
        assertThat(actual)
            .as("Verify Collection relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getLookImageUrl()).as("check lookImageUrl").isEqualTo(expected.getLookImageUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionUpdatableRelationshipsEquals(Collection expected, Collection actual) {
        assertThat(actual)
            .as("Verify Collection relationships")
            .satisfies(a -> assertThat(a.getProducts()).as("check products").isEqualTo(expected.getProducts()));
    }
}
