package com.lumiere.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FlashSaleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleAllPropertiesEquals(FlashSale expected, FlashSale actual) {
        assertFlashSaleAutoGeneratedPropertiesEquals(expected, actual);
        assertFlashSaleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleAllUpdatablePropertiesEquals(FlashSale expected, FlashSale actual) {
        assertFlashSaleUpdatableFieldsEquals(expected, actual);
        assertFlashSaleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleAutoGeneratedPropertiesEquals(FlashSale expected, FlashSale actual) {
        assertThat(actual)
            .as("Verify FlashSale auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleUpdatableFieldsEquals(FlashSale expected, FlashSale actual) {
        assertThat(actual)
            .as("Verify FlashSale relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleUpdatableRelationshipsEquals(FlashSale expected, FlashSale actual) {
        // empty method
    }
}
