package com.lumiere.app.domain;

import static com.lumiere.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FlashSaleProductAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleProductAllPropertiesEquals(FlashSaleProduct expected, FlashSaleProduct actual) {
        assertFlashSaleProductAutoGeneratedPropertiesEquals(expected, actual);
        assertFlashSaleProductAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleProductAllUpdatablePropertiesEquals(FlashSaleProduct expected, FlashSaleProduct actual) {
        assertFlashSaleProductUpdatableFieldsEquals(expected, actual);
        assertFlashSaleProductUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleProductAutoGeneratedPropertiesEquals(FlashSaleProduct expected, FlashSaleProduct actual) {
        assertThat(actual)
            .as("Verify FlashSaleProduct auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleProductUpdatableFieldsEquals(FlashSaleProduct expected, FlashSaleProduct actual) {
        assertThat(actual)
            .as("Verify FlashSaleProduct relevant properties")
            .satisfies(a ->
                assertThat(a.getSalePrice()).as("check salePrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSalePrice())
            )
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getSold()).as("check sold").isEqualTo(expected.getSold()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlashSaleProductUpdatableRelationshipsEquals(FlashSaleProduct expected, FlashSaleProduct actual) {
        assertThat(actual)
            .as("Verify FlashSaleProduct relationships")
            .satisfies(a -> assertThat(a.getFlashSale()).as("check flashSale").isEqualTo(expected.getFlashSale()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
