package com.lumiere.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LoyaltyTransactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoyaltyTransactionAllPropertiesEquals(LoyaltyTransaction expected, LoyaltyTransaction actual) {
        assertLoyaltyTransactionAutoGeneratedPropertiesEquals(expected, actual);
        assertLoyaltyTransactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoyaltyTransactionAllUpdatablePropertiesEquals(LoyaltyTransaction expected, LoyaltyTransaction actual) {
        assertLoyaltyTransactionUpdatableFieldsEquals(expected, actual);
        assertLoyaltyTransactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoyaltyTransactionAutoGeneratedPropertiesEquals(LoyaltyTransaction expected, LoyaltyTransaction actual) {
        assertThat(actual)
            .as("Verify LoyaltyTransaction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoyaltyTransactionUpdatableFieldsEquals(LoyaltyTransaction expected, LoyaltyTransaction actual) {
        assertThat(actual)
            .as("Verify LoyaltyTransaction relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getPoints()).as("check points").isEqualTo(expected.getPoints()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoyaltyTransactionUpdatableRelationshipsEquals(LoyaltyTransaction expected, LoyaltyTransaction actual) {
        assertThat(actual)
            .as("Verify LoyaltyTransaction relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
