package com.lumiere.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductQuestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductQuestionAllPropertiesEquals(ProductQuestion expected, ProductQuestion actual) {
        assertProductQuestionAutoGeneratedPropertiesEquals(expected, actual);
        assertProductQuestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductQuestionAllUpdatablePropertiesEquals(ProductQuestion expected, ProductQuestion actual) {
        assertProductQuestionUpdatableFieldsEquals(expected, actual);
        assertProductQuestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductQuestionAutoGeneratedPropertiesEquals(ProductQuestion expected, ProductQuestion actual) {
        assertThat(actual)
            .as("Verify ProductQuestion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductQuestionUpdatableFieldsEquals(ProductQuestion expected, ProductQuestion actual) {
        assertThat(actual)
            .as("Verify ProductQuestion relevant properties")
            .satisfies(a -> assertThat(a.getAuthor()).as("check author").isEqualTo(expected.getAuthor()))
            .satisfies(a -> assertThat(a.getQuestionText()).as("check questionText").isEqualTo(expected.getQuestionText()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductQuestionUpdatableRelationshipsEquals(ProductQuestion expected, ProductQuestion actual) {
        assertThat(actual)
            .as("Verify ProductQuestion relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
