package com.lumiere.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductAnswerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAnswerAllPropertiesEquals(ProductAnswer expected, ProductAnswer actual) {
        assertProductAnswerAutoGeneratedPropertiesEquals(expected, actual);
        assertProductAnswerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAnswerAllUpdatablePropertiesEquals(ProductAnswer expected, ProductAnswer actual) {
        assertProductAnswerUpdatableFieldsEquals(expected, actual);
        assertProductAnswerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAnswerAutoGeneratedPropertiesEquals(ProductAnswer expected, ProductAnswer actual) {
        assertThat(actual)
            .as("Verify ProductAnswer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAnswerUpdatableFieldsEquals(ProductAnswer expected, ProductAnswer actual) {
        assertThat(actual)
            .as("Verify ProductAnswer relevant properties")
            .satisfies(a -> assertThat(a.getAuthor()).as("check author").isEqualTo(expected.getAuthor()))
            .satisfies(a -> assertThat(a.getAnswerText()).as("check answerText").isEqualTo(expected.getAnswerText()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAnswerUpdatableRelationshipsEquals(ProductAnswer expected, ProductAnswer actual) {
        assertThat(actual)
            .as("Verify ProductAnswer relationships")
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()));
    }
}
