package com.lumiere.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductReviewAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReviewAllPropertiesEquals(ProductReview expected, ProductReview actual) {
        assertProductReviewAutoGeneratedPropertiesEquals(expected, actual);
        assertProductReviewAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReviewAllUpdatablePropertiesEquals(ProductReview expected, ProductReview actual) {
        assertProductReviewUpdatableFieldsEquals(expected, actual);
        assertProductReviewUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReviewAutoGeneratedPropertiesEquals(ProductReview expected, ProductReview actual) {
        assertThat(actual)
            .as("Verify ProductReview auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReviewUpdatableFieldsEquals(ProductReview expected, ProductReview actual) {
        assertThat(actual)
            .as("Verify ProductReview relevant properties")
            .satisfies(a -> assertThat(a.getRating()).as("check rating").isEqualTo(expected.getRating()))
            .satisfies(a -> assertThat(a.getAuthor()).as("check author").isEqualTo(expected.getAuthor()))
            .satisfies(a -> assertThat(a.getComment()).as("check comment").isEqualTo(expected.getComment()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReviewUpdatableRelationshipsEquals(ProductReview expected, ProductReview actual) {
        assertThat(actual)
            .as("Verify ProductReview relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
