package com.lumiere.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StockNotificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockNotificationAllPropertiesEquals(StockNotification expected, StockNotification actual) {
        assertStockNotificationAutoGeneratedPropertiesEquals(expected, actual);
        assertStockNotificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockNotificationAllUpdatablePropertiesEquals(StockNotification expected, StockNotification actual) {
        assertStockNotificationUpdatableFieldsEquals(expected, actual);
        assertStockNotificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockNotificationAutoGeneratedPropertiesEquals(StockNotification expected, StockNotification actual) {
        assertThat(actual)
            .as("Verify StockNotification auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockNotificationUpdatableFieldsEquals(StockNotification expected, StockNotification actual) {
        assertThat(actual)
            .as("Verify StockNotification relevant properties")
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getNotified()).as("check notified").isEqualTo(expected.getNotified()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockNotificationUpdatableRelationshipsEquals(StockNotification expected, StockNotification actual) {
        assertThat(actual)
            .as("Verify StockNotification relationships")
            .satisfies(a -> assertThat(a.getProductVariant()).as("check productVariant").isEqualTo(expected.getProductVariant()));
    }
}
