package com.lumiere.app.domain;

import static com.lumiere.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class VoucherAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoucherAllPropertiesEquals(Voucher expected, Voucher actual) {
        assertVoucherAutoGeneratedPropertiesEquals(expected, actual);
        assertVoucherAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoucherAllUpdatablePropertiesEquals(Voucher expected, Voucher actual) {
        assertVoucherUpdatableFieldsEquals(expected, actual);
        assertVoucherUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoucherAutoGeneratedPropertiesEquals(Voucher expected, Voucher actual) {
        assertThat(actual)
            .as("Verify Voucher auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoucherUpdatableFieldsEquals(Voucher expected, Voucher actual) {
        assertThat(actual)
            .as("Verify Voucher relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getUsageLimit()).as("check usageLimit").isEqualTo(expected.getUsageLimit()))
            .satisfies(a -> assertThat(a.getUsageCount()).as("check usageCount").isEqualTo(expected.getUsageCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoucherUpdatableRelationshipsEquals(Voucher expected, Voucher actual) {
        // empty method
    }
}
